# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6e6fa6908c0478702a8ee0e43f70a5094535749c0caa365f753d9ad5b3f54f2e813cc5b0e0f0d56c2c03653b2b1db5194a4a2de4d121053149beee7d52a306ce

test:
  secret_key_base: bf726286bab7988e686f470841fa6c8865842c7374df14a849290543d3253903189b508b3e779039dd6d7f46dcb1301b0c9882de45dc6d2faf27475fe3ca7591

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
